README.md

Unfortunately, the wiki claims the contents are out of date, and can't seem to find the latest wiki revision.

All: Adding a web link to MurmurHash3.

---

doc/mgba-qt.6
doc/mgba.6

My first instinct when about to use a new emulator is to check the manpage, so I can see the command line flags and default keybindings.
I don’t know what magic CMake needs to install it in the man directories.
Gave it MPL 2.0. Would prefer something simpler like MIT honestly, but figured it was better to be consistent with the rest of mgba (unless you’re willing to relicense…).

Add a manpage for mgba.

---

src/gba/renderers/software-bg.c
src/gba/renderers/software-private.h

Silences a load of warnings when compiling with GCC 5.2.1

software renderer: Silence -Wlogical-not-parentheses warnings

---

src/platform/qt/GameController.cpp

mgba-qt hangs if you reset the emulator while it is paused.  Subsequently unpausing the emulator does not resolve the hang, although reloading the rom does.
The immediate cause of the hang is that the CPU thread is waiting for the audioRequiredCond condition in GBASyncProduceAudio.  This condition never gets raised because AudioProcessorSDL has paused the audio.  Because the thread's state was set to THREAD_RUNNING by the reset, none of the unpause handlers will get called.
I've solved this by unpausing the emulator before resetting it.

Unpause the emulator when resetting.

---

README.md

A bit frustrated when clicking the Travis-CI icon gets me a page with the same icon.
:P

Readme: Jumps to project page when clicking the Travis-CI icon

---

CHANGES
src/gba/gba.c
src/gba/memory.c
src/gba/memory.h
src/gba/vfame.c
src/gba/vfame.h

This adds support for the copy protection used in games by the Taiwanese unlicensed company Vast Fame. These use somewhat unique cartridge hardware which allows for various manipulations of SRAM writes and ROM reads to thwart attempts at dumping and emulation.
There aren't any dumps of these games publicly available (at least not the original versions; a couple dumps of hacked reprints are floating around, but they have their own problems) - I have three which I intend to release on my blog once emulator support is in place, and those seem to run fine with my changes. If you'd like a copy of the roms for testing let me know.

GBA Memory: Add emulation of Vast Fame protected carts

---

src/util/vfs/vfs-zip.c

According to CmakeLists.txt file USE_MINIZIP enables linking against system
minizip library but the code in src/util/vfs/vfs-zip.c doesn't reflect that.

Don't include internal zip library when USE_MINIZIP is defined.

---

CHANGES
src/platform/qt/DisplayQt.cpp

When the aspect ratio is locked and the window's aspect ratio is wider than the game boy's, the Qt software renderer divides the width by 2 instead of the game boy's height.  As a result, the video is way too wide.
Here's what it looks like without this fix:
Here's what it looks like with this fix:

Qt: Fix software renderer scaling

---

CHANGES
src/platform/qt/GameController.cpp

When disabling the autofire option the key is sometimes left in the pressed status, causing it to ignore further button presses. This change forces the key to be released in those cases.

Qt: Reset button status after turning off autofire

---

doc/mgba-qt.6
doc/mgba.6
src/core/config.c

I didn’t change the documentation because most users will keep `XDG_CONFIG_HOME` empty, and those who do will already know about it.

Core: Obey the XDG basedir specification for environment variables

---

CHANGES
src/gba/cheats/gameshark.c

The address for GameShark ROM patch codes was being incorrectly calculated.  It appears that ActionReplay ROM patch codes were fixed in 3a3b7dffdb9e69763a9567119e45312d4b1453df, but no such fix was made for GameShark codes.

GBA Cheats: Fix GameShark ROM patches

---

CHANGES
src/gba/vfame.c

Adds support for a feature of Vast Fame protected carts used by a newly dumped game, Mo Jie Qi Bing (aka Lord of the Rings). 
Also adds detection for this game based on its title, because it's based on Kiki KaiKai Advance and doesn't share the usual initialisation routine used to detect other Vast Fame games.

GBA Memory: Support for Mo Jie Qi Bing by Vast Fame

---

CHANGES
src/platform/libretro/libretro.c

From https://github.com/libretro/mgba/pull/45

Fix missing termination in call to SET_INPUT_DESCRIPTORS

---

include/mgba/internal/gba/sio.h

I noticed that the layout of the normalControl struct in [sio.h](https://github.com/mgba-emu/mgba/blob/9942c1d44440d22ad0e7fd5ec58b3bdbe4efd92d/include/mgba/internal/gba/sio.h#L52-L64) is incorrect. According to [GBATEK](http://problemkaputt.de/gbatek.htm#sionormalmode), the first unused section is 3 bits long (bits 4,5,6) and the second is 4 bits long (8,9,10,11). mGBA has 4 bits in the first section unused (bits 4,5,6,7) and 3 in the second section (bits 9,10,11). As a consequence, `sio.normalControl.start` is in the wrong place. A minor bug that doesn't appear to affect mGBA currently, but will be a barrier to work on the wireless adapter.

GBA SIO: Fix layout of normalControl struct in siocnt union

---

README.md

This adds the commands you need to use if you want to build for x86_64 (64-bit) with MSYS2. It also adds a link to the tool called "Dependency Walker" which is able to tell you which additional DDLs you have to ship if you *really* want to distribute a MSYS2-compiled mGBA binary for testing purposes.
I use the 64 bit version of MSYS2/MinGW-w64 myself, so all commands are verified by myself.

Doc: Improve notes for MSYS2

---

include/mgba/core/version.h

Needed by MSVC. Somehow missed this in last commit.

Add 'extern "C"' guards to version.h.

---

README.md

I accidentally used the wrong names for the Start Menu entries of the different MSYS2 shells.

Doc: Fix MSYS2 shortcut names in README.md

---

src/debugger/gdb-stub.c

First of all, thanks for developing this neat piece of software! Now, to the patch.
The GDB stub in mgba has a critical problem (has nobody come across this before ? am I the only one using it ;) ?). The 'g' request needs to return the cpu status register for the ARM remote GDB protocol, otherwise debugger interfaces such as IDA cannot detect whether the CPU is in ARM or THUMB mode (the 'T' bit). In particular, if you don't return anything, IDA just assumes that it is always in ARM mode, and then destroys all of the instructions in your disassembly which use THUMB by forcing them to be decoded as ARM (even if the analysis thinks they should be THUMB). 
This patch fixes that.

Fix GDB stub reporting of CPSR

---

src/platform/qt/GBAApp.cpp
src/platform/qt/GBAApp.h
src/platform/qt/GameController.cpp
src/platform/qt/ObjView.cpp
src/platform/qt/PaletteView.cpp
src/platform/qt/Window.cpp

The core still gets '/'s always (it chokes on '\'s), but the Qt
interface always uses the native separators.
In the process of doing this, also removed the custom FileDialog
subclass and made everything use GBAApp::get*FileDialog instead.
Also fixes #552, because I had to change that code anyway.

 	Qt: Show native directory separators in the GUI.

---

src/platform/python/_builder.py

Before fix:
```
/usr/bin/ld: cannot find -lmgba
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
python/CMakeFiles/medusa-emu-py.dir/build.make:62: recipe for target 'python/build/lib/medusa-emu/__init__.py' failed
make[2]: *** [python/build/lib/medusa-emu/__init__.py] Error 1
CMakeFiles/Makefile2:159: recipe for target 'python/CMakeFiles/medusa-emu-py.dir/all' failed
make[1]: *** [python/CMakeFiles/medusa-emu-py.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

Fix Python build libraries

---

src/core/input.c

Previously the binding struct wouldn't be fully invalidated.
Do you want me to add an entry to the CHANGES doc for this? (guidelines don't say whether or not to update them).

Core Input: Correct a memset size within mInputUnbindHat()

---

res/shaders/fish.shader/fish.fs
res/shaders/fish.shader/manifest.ini

I created a new 2x upscale shader that tries to keep thin lines thin. It's not as beautiful as HQX or XBR, but may be very good for games that have a lot of horizontal, vertical and diagonal lines. Here's a visual comparison:

New shader

---

src/platform/qt/AssetTile.cpp
src/platform/qt/AssetView.cpp
src/platform/qt/CheatsView.cpp
src/platform/qt/ConfigController.cpp
src/platform/qt/DebuggerConsole.cpp
src/platform/qt/DebuggerController.cpp
src/platform/qt/Display.cpp
src/platform/qt/DisplayGL.cpp
src/platform/qt/GBAKeyEditor.cpp
src/platform/qt/GDBWindow.cpp
src/platform/qt/GIFView.cpp
src/platform/qt/GameController.cpp
src/platform/qt/IOViewer.cpp
src/platform/qt/LoadSaveState.cpp
src/platform/qt/LogController.cpp
src/platform/qt/LogView.cpp
src/platform/qt/MemoryModel.cpp
src/platform/qt/MemoryModel.h
src/platform/qt/MemoryView.cpp
src/platform/qt/MessagePainter.cpp
src/platform/qt/ObjView.cpp
src/platform/qt/OverrideView.cpp
src/platform/qt/PaletteView.cpp
src/platform/qt/SensorView.cpp
src/platform/qt/SettingsView.cpp
src/platform/qt/ShaderSelector.cpp
src/platform/qt/ShortcutView.cpp
src/platform/qt/TileView.cpp
src/platform/qt/VideoView.cpp
src/platform/qt/Window.cpp

A few connect()s have not been migrated because the best way to migrate them requires somewhat invasive changes. Other than that, everything has been moved over.
~~The FFmpeg/GIF export changes **have not been tested** and are almost certainly busted because I don't have FFmpeg or ImageMagick here to test, so don't merge until Travis passes.~~ Fixed now.

Qt: Switch to the C++11 connect() syntax.

---

src/platform/qt/ts/mgba-de.ts

The German translation now contains all the new strings
introduced since the last update. Except the IOViewer stuff. Again.

Qt: Update German GUI translation

---

src/core/thread.c
src/gb/core.c
src/gba/core.c

When building with `cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_LIBRETRO=1` the resulting lib has undefined symbols that cause issues when loading the libretro core in GDB.
~~~
$ ldd -r mgba_libretro.so
undefined symbol: GBAVideoProxyRendererCreate (./mgba_libretro.so)
undefined symbol: GBAVideoProxyRendererUnshim (./mgba_libretro.so)
undefined symbol: GBAVideoProxyRendererShim (./mgba_libretro.so)
undefined symbol: GBVideoProxyRendererCreate (./mgba_libretro.so)
undefined symbol: GBVideoProxyRendererUnshim (./mgba_libretro.so)
undefined symbol: GBVideoProxyRendererShim (./mgba_libretro.so)
undefined symbol: mVideoLogContextInitialState (./mgba_libretro.so)
undefined symbol: mVideoLoggerAddChannel (./mgba_libretro.so)
undefined symbol: mVideoLoggerAttachChannel (./mgba_libretro.so)
undefined …

Fix undefined symbols when compiling libretro core as debug build

---

src/platform/qt/MemoryModel.cpp

Fixes "MemoryModel.cpp:102:15: error: no viable overloaded '='"

Qt: Fix build with Qt 5.10

---

src/platform/libretro/libretro.c

This patch adds an option in RetroArch to enable or disable Super Game Boy borders.

Libretro: Add SGB border option

---

README.md
README_DE.md

The libepoxy library is required for shader support.

Doc: Add "libepoxy" to msys/mingw-w64 dependencies

---

src/platform/libretro/libretro.c

This adds a switch in RetroArch to force the Game Boy model to Game Boy, Game Boy Color, or Super Game Boy.  The default setting is "Autodetect," which preserves the current behavior of selecting the most appropriate model for the current game.
In order to support running DMG games with one of the Game Boy Color's built-in palettes, the RetroArch core will now also attempt to load the BIOS for the selected Game Boy model.

Libretro: Allow choosing the Game Boy model

---

src/gb/renderers/software.c
src/platform/libretro/libretro.c

This fixes an issue with Pokemon Blue's SGB border:
According to the [Pan Docs](http://problemkaputt.de/pandocs.htm#sgbcolorpalettesoverview), "Color 0 of each of the eight palettes is transparent, causing the backdrop color to be displayed instead".  The output buffer needed to be initialized to white for this border to display correctly, which also has a nice side effect of preventing a border of garbage from briefly displaying before boot:
I updated the libretro version to initialize the output buffer; the Qt version already initializes its buffer to all 1s.  I haven't tried any other platforms, so they may also need to be be updated.
Thanks for taking the time to look at these changes, and thank you for making this wonderful emulator!

GB Video: Fix SGB border transparency

---

src/gb/gb.c
src/platform/libretro/libretro.c

If the Game Boy Color model is set to Game Boy Advance, it only works as expected if the "Use BIOS" option is false or "Skip BIOS" is true.  `GBSkipBIOS` sets register B to 1 (which games can use to determine if they are running on a GBA), but register B never gets set when loading a real boot ROM.
Maybe there's a better approach (and I'd be happy to change this if there is), but this patches the GBC boot ROM to load 1 into B when the model is set to GBA.  There are two bytes of `NOOP` near the end of the main routine, which gives us exactly enough room to add the new instruction without compromising anything else.  It's almost too good to be a coincidence, and makes me wonder if the GBA contains a modified GBC boot ROM that works exactly like this...
Anyway, I tested this with Oracle of …

GB: Fix GBC games running on GBA with BIOS

---

src/gb/renderers/software.c

While rewinding, some areas of the screen (usually status bars and text boxes) shift down by one pixel.  I bisected to a6a6e31169f98 and looked for possible off-by-one errors.  I haven't spent much time reading this part of the code, so I don't know if this patch is the "right" fix, but it seems to resolve the issue.

GB Video: Fix windows shifting down by one pixel when rewinding

---

src/platform/python/_builder.py
src/platform/python/setup.py.in

OS: Debian 10 "buster"
Currently, if libmgba is installed to a path which is not on the system's library search path, importing the python library fails:
```
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mgba
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/callie/.local/lib/python3.6/site-packages/mgba/__init__.py", line 6, in <module>
from ._pylib import ffi, lib
ImportError: libmgba.so.0.7: cannot open shared object file: No such file or directory
```
This PR adds the lib install directory of the build as a runtime library search path, solving the issue.

Python: Add runtime library search path

---

doc/mgba.6

This fixes the following warning found with mandoc's lint feature for the `mgba.6` man page.
In short `mgba.6` contains a cross reference to itself which seems to not be the best practice, `mandoc(1)` suggests using a `.Nm` or `.Fn` macro instead of `.Xr`, but in this case I just removed the `.Xr` macro and added the mgba reference in the existing text which seems to work out. I chose to omit the `(6)` as it seemed silly to have a reference to a man page I was currently reading. :)
Any suggestions are of course welcome.
```
man -Tlint mgba
```
```
man: mgba.6.gz:247:5: WARNING: cross reference to self: Xr mgba 6
```
```
cross reference to self
(mdoc) An Xr macro refers to a name and section matching the section
of the present manual page and a name mentioned in an Nm macro in
the NAME or …
```

man: Silence mgba.6 mandoc warning.

---

README.md
README_DE.md

"git" is obviously needed for pulling the latest source code.
"base-devel" is needed to actually make the compiler toolchain work.
Both packages are not installed in current MSYS2 base installations.

Doc: Add git and base-devel to MSYS2 dependencies

---

src/gba/gba.c

At the moment mGBA doesn't zero the DebugString buffer in [`GBADebug`](https://github.com/mgba-emu/mgba/blob/master/src/gba/gba.c#L521-L532) after copying a message out into `oolBuf`; if I don't either, and happen to use a message which is shorter than the one which came before it, odd things happen.

GBA: Zero DebugString buffer when handling messages

---

CHANGES
src/gba/io.c

Regression in 254721697244411011ab687dad5c18a8c0f2de49 (between 0.3.2 and 0.4.0). This should be allowed according to GBATEK and fixes RavenWorks' Organya player: http://raven.works/projects/cavestory/organya.gba

GBA I/O: SOUNDCNT_HI is readable when sound is off

---

src/platform/sdl/CMakeLists.txt
src/platform/sdl/gles2-sdl.c
src/platform/sdl/main.h
src/platform/sdl/rpi-common.c
src/platform/sdl/rpi-common.h

I'm not sure if this works, or if it's even needed anymore since we now support SDL2, but moving this to a separate file makes things easier to maintain.

SDL: Move Raspberry Pi initialisation code to a separate file

---

CMakeLists.txt
include/mgba-util/platform/posix/threading.h

This should be less platform-specific than the previous checks. Not all platforms have been tested, though.

CMake: Improved detection of pthreads.

---

src/platform/cmake/FindSDL2.cmake
src/platform/sdl/CMakeLists.txt

Sorry, I forgot to send this patches that does fix SDL2 package search (Apperently pkg find look for different names than the one that were originally in FindSDL2.cmake)

SDL: Fix search package

---

include/mgba-util/common.h

Under Microsoft Visual C++ 2019, exporting the costructor causes build issue with mgba-qt port.
Removing the line does fix some compilation issue (and actually some linking issue with Qt).

Util: Removed broken dllexport symbol

---

src/platform/qt/CMakeLists.txt

With the old method, the user have to manually specify the Qt5 folders for each component (Under CMake for Windows), like Qt5_Widgets_Dir, Qt5_Network_Dir and so on.
Using this method simplify searching for the required modules, as the user only have to fit Qt5_Dir with the directory of Qt5Config.cmake and all the other modules will be still found without specifying where they are.

Simplified QT5 module search

---

include/mgba/core/log.h
include/mgba/gba/interface.h
include/mgba/internal/gb/io.h
include/mgba/internal/gba/io.h
include/mgba/internal/gba/video.h
src/gb/io.c
src/gba/hardware.c
src/gba/video.c

This commit adds the ability to export the required function for building mgba-qt with Microsoft Visual C++.
Note: When launching a GBA game with Display mode different than Software (Qt), the emulator crashes. (reg-fifo.c at line 38).

All: Added exports for qt

---

.github/FUNDING.yml

Changes proposed in this request:
- Adds the GitHub sponsors button. Here's an example with playnite:
https://github.com/JosefNemec/Playnite
Info from GitHub on this below:
```
.github/FUNDING.yml shows the community how to support this project. Please see our repository funding links [documentation ](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository) for more information on formatting and what is and isn't allowed in this file.
Please note that funding links are currently disabled on this repository. Visit repository settings to enable display of your funding links.
```

Add GitHub sponsors button to feature patreon

---

src/platform/windows/setup/setup.iss.in

The current way to check if we are running a 64 bit version of Windows
in order to detect the proper path ("Program Files" or "Program Files
(x86)") doesn't work, thus even the 64 bit version is installed in the
32 bit Program Files folder.
The check itself is not necessary, since Inno Setup is smart enough to
check the platform it's running on and chooses the proper path and
registry settings by itself.

Win32: Fix x64 installation paths

---

src/platform/qt/CoreController.cpp
src/platform/qt/MapView.cpp
src/platform/qt/OverrideView.cpp

GB specific code was added without guards, causing configurations with
it disabled to fail compiling:
cmake -B build -DM_CORE_GB:BOOL=OFF
Resolves: #1578
Fixes: a44a8f668f6a5 ("GB: Add yanking")
Fixes: fbe375fab992c ("Core: Add support for caching bitmapped modes")
Fixes: 06657d9fde5a2 ("Qt: Add additional info to map view")
Fixes: f15aacd0b6aaf ("Qt: Set default Game Boy colors")

Qt: Fix compiling with M_CORE_GB disabled

---

include/mgba/internal/arm/arm.h

This was breaking mGBA rather badly on my PPC little-endian host, starting from bf8c1d1b4b52d45cd84590dc7bd7d40b0dffc7bd with the introduction of the `#if defined(__BIG_ENDIAN__)` below the one I changed here.
Optimistically, this fix might also help more than just folks with modern POWER systems -- after all, not all PowerPC hosts are big-endian, and PowerPC isn't the only big-endian architecture.
Cheers
-lif

Use consistent conditionals for big endian detection in PSR union

---

src/gba/ereader.c

With this change, it builded (at least for me) fine under Visual Studio 2019 (vcpkg + manual libepoxy)

GBA: Fix msvc compilation

---

CHANGES
src/core/core.c
src/platform/qt/SettingsView.cpp
src/platform/qt/SettingsView.ui
src/platform/qt/Window.cpp

This implements the feature requested in #1784 
One caveat: the best source of data I could find for the currently loaded ROM's file name was the `baseName` field of the `mDirectorySet` struct (the instance held by `mCore`). However, this doesn't seem to carry the file extension.
So, if you loaded the file `pokemon-fire-red.gba`, you would only see `pokemon-fire-red`.

Setting to show filename in title bar instead of ROM name.

---

src/platform/qt/ts/mgba-it.ts

Title.
Looking at the other languages this should fix it.
Closes #1798 
In the spanish localization the hours were HH and not hh, is there a particular reason?

Fix italian real time clock translation

---

include/mgba/internal/arm/decoder-inlines.h
include/mgba/internal/arm/isa-inlines.h
src/arm/debugger/debugger.c
src/debugger/gdb-stub.c
src/debugger/stack-trace.c

The stack trace implementation from the last PR didn't account for calling conventions common on the GBA and had some noteworthy oversights. This PR adds support for:
* calling a function by writing to `lr` followed by `b` or `bx` (since ARMv4 doesn't have `blx`)
* returning from a function using `mov pc, lr` (oops!)
* heuristically determining if `mov pc, rN` is meant to be a function return based on `sp` and `pc`
* skipped/unwound stack frames
* branches not taken (oops!)
* two-instruction `bl` in Thumb mode
It also cleans up backtrace rendering and some cosmetic miscalculations.

Stack traces: add detection for other calling conventions and stack manipulation

---

CHANGES
include/mgba-util/table.h
include/mgba/internal/debugger/cli-debugger.h
include/mgba/internal/debugger/stack-trace.h
include/mgba/internal/debugger/symbols.h
src/debugger/CMakeLists.txt
src/debugger/cli-debugger-scripting.c
src/debugger/cli-debugger.c
src/debugger/stack-trace.c
src/debugger/symbols.c
src/platform/sdl/main.c
src/util/table.c

mGBA can already load symbols out of ELF files (and I think there's work being done on loading them from separate sym files). This PR adds the ability to define new symbols in the CLI debugger and to resolve addresses to their matching symbol table entries in stack traces.
As a bonus feature, it also adds a new scripting engine to allow running a list of debugger commands from a file. It's pretty simplistic, but it does the job.

Debugger: define symbols in CLI, show symbols in stack traces

---

src/platform/psp2/psp2-context.c

This pull request should fix issue #1689. I've also reduced the size of vita2d_texture from 4 to 2; I haven't found anything that needs 4 buffers rather than 2, and interframe blending works with 2 buffers.

Vita: Fix flickering when using frameskip

---

src/debugger/stack-trace.c

Just a minor bugfix because I switched a couple things around during a refactor and broke it.

Stack traces: fix flipped variables that cause a crash

---

include/mgba/internal/arm/decoder-inlines.h
src/arm/debugger/debugger.c

This is the same as #1832 but for the medusa branch. The primary difference is in how the condition abstraction is handled in order to support ARMv5.

medusa: stack trace fixes

---

include/mgba/internal/arm/decoder.h
include/mgba/internal/arm/isa-inlines.h
src/arm/arm.c
src/arm/debugger/debugger.c
src/arm/decoder.c
src/debugger/cli-debugger.c

I noticed totally bogus pointers in stack traces and it turns out I had misunderstood what the decoder was referring to as "indirect" branches. Also having interrupt handlers switch around the stack pointer was causing frames to be spuriously popped.

Stack traces: fix tracing of indirect jumps and interrupt handlers

---

src/debugger/symbols.c

This basically implements what I asked for a while back in comment on #1260, adding support for a slight variation on the symfile format, which includes sizes. ARMIPS outputs this format when supplied with `-sym2` (as opposed to `-sym`); the ARMIPS readme says that it was originally from PCSX2 and PPSSPP, and gives the following example:
```
00000000 0
80000000 .dbl:0010
80000010 Main
8000002C Subroutine,0000001C
80240000 NewBlock,00000014
```
As is, mGBA will parse that and create symbols called `Subroutine,0000001C` and `NewBlock,00000014`. This PR basically just checks for a comma in the name of a symbol in a symfile and throws away it and everything after it (so they'd be correctly identified as `Subroutine` and `NewBlock`).
It's a fairly trivial change, but I'm not overly confidant …

Support variant symfile format with function sizes

---

src/platform/qt/InputController.cpp
src/platform/qt/InputController.h

This member could be accessed at the same from different threads leading
to random (rare) crashes.
Fixes #1875

Fix a race condition on `InputController::m_pendingEvents`

---

src/platform/libretro/libretro.c

Otherwise, if the frontend does not support GET_CAMERA_INTERFACE,
the start and stop functions are NULL, causing a crash when a gameboy
ROM is unloaded.

Libretro: Only set camera peripheral when it is available

---

src/gba/memory.c

According to GBATEK unused memory is filled the following way:
> Because Gamepak uses the same signal-lines for both 16bit data and for lower 16bit halfword address, the entire gamepak ROM area is effectively filled by incrementing 16bit values (Address/2 AND FFFFh).
mGBA already adheres to that in word / halfword loads but the byte variant seems to be wrong. Currently it returns the same value for both bytes of the actual 16bit value. Please correct me if I am wrong here.

Return correct byte in out of bounds ROM load

---

src/gba/overrides.c

I got a physical copy of the game, dumped the save data, and tried to get it to work with mGBA, But this game was not detected correctly in autodetect.
It uses EEPROM, seems like the same PCB as the Dragon Ball Z - The Legacy of Goku.

GBA: Add override for DigiCommunication Nyo

---

src/platform/qt/LogConfigModel.cpp

The Qt interface's logging configuration UI has a checkbox in the top-left corner that doesn't make sense: what does it mean to set the default logging level to be the default logging level?
The practical effect of this is that if you check that box, it checks all of the levels and then you can't uncheck it afterward.
This PR removes the checkbox from that space in the grid. It also fixes a harmless cosmetic issue that allows users to type in cells -- this doesn't do anything, but there's no reason to indicate that the cells can be typed in.

Don't make the top-left square of the logging grid checkable

---

src/debugger/gdb-stub.c

This needs some context because the T command became needed due to this ghidra issue I encountered while trying to setup a debugging environment with ghidra's debugger connected to mgba's gdb stub. The issue thread can be found here: https://github.com/NationalSecurityAgency/ghidra/issues/3452
Essentially, ghidra will send a T command to gdb for a lot of its functions to make sure the thread you are currently debugging is still alive, but mgba did not support that command. It supports H, but that one is implemented by faking it since mgba only operates on one thread. 
Since the ONLY thread mgba operates on should still be alive when the gdb stub is active, it would make sense for the same reasons to simply fake it the same way for the T command and since I got very good success to setup a …

gdb-stub: Add support for the T command by faking it

---

include/mgba-util/threading.h

msvc currently supports up to c17 but does not implement some optional features. see https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160 and https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160

msvc : fix compilation for c11/c17 lang standards

---

src/platform/qt/SettingsView.cpp
src/platform/qt/SettingsView.ui
src/platform/qt/ts/mgba-de.ts
src/platform/qt/ts/mgba-en.ts
src/platform/qt/ts/mgba-es.ts
src/platform/qt/ts/mgba-fi.ts
src/platform/qt/ts/mgba-fr.ts
src/platform/qt/ts/mgba-hu.ts
src/platform/qt/ts/mgba-it.ts
src/platform/qt/ts/mgba-ja.ts
src/platform/qt/ts/mgba-ko.ts
src/platform/qt/ts/mgba-ms.ts
src/platform/qt/ts/mgba-nb_NO.ts
src/platform/qt/ts/mgba-nl.ts
src/platform/qt/ts/mgba-pl.ts
src/platform/qt/ts/mgba-pt_BR.ts
src/platform/qt/ts/mgba-ru.ts
src/platform/qt/ts/mgba-template.ts
src/platform/qt/ts/mgba-tr.ts
src/platform/qt/ts/mgba-zh_CN.ts

The language selection dropdown lists the supported languages written in themselves for every language except English. English gets translated into the language of the active locale.
Bizarrely, this results in "English" being translated as "português do Brasil" when the system locale is set to Portugal Portuguese. THIS appears to be a bug in Qt, not a bug in mGBA, but it motivates fixing the above issue.

Fix "English" language name

---

src/debugger/gdb-stub.c

This will always put a hardware breakpoint regardless if GDB sends a software or hardware breakpoint.
The reason for this is simple: software breakpoints can be very unreliable for determining if we are in Thumb or ARM mode. I can even get setups to be able to consistently reproduce this problem (I even get this issue in arm-none-ebai-gdb which is supposed to be more targetted for what we want here). A wrong guess by GDB can be fatal as mgba could add an ARM breakpoint in Thumb code and it just so happen that in Thumb, the first half of the bkpt instruction corresponds to a branch a bit further in the code, atrocities ensures, but usually ends up in SIGILL and mgba SPAMMING errors.
I also don't think we should be letting GDB decide the kind of breakpoints between ARM and Thumb: mgba …

GDB Stub: use only hardware breakpoints regardless of GDB's request

---

src/feature/ffmpeg/ffmpeg-decoder.c
src/feature/ffmpeg/ffmpeg-encoder.c

Hello,
Debian's FFmpeg maintainers reported that mgba fails to compile using the newly released FFmpeg 5.0.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004768
I have compiled, run `mgba-cinema`, and briefly tested video and GIF encoding with these changes on Debian unstable, with both FFmpeg 4.4 and 5.0.
I'm not sure about all the `const` additions. The FFmpeg 5.0 APIs return `const` pointers, but there are places with both versions where the pointers are passed to functions taking `void *`, which of course causes a new warning. I don't really know what's less bad here; at least `const` makes sure mGBA itself is sane?

FFmpeg: Support FFmpeg 5.0

---

include/mgba/internal/debugger/gdb-stub.h
src/debugger/debugger.c
src/debugger/gdb-stub.c
src/platform/qt/GDBController.cpp
src/platform/qt/GDBController.h
src/platform/qt/GDBWindow.cpp
src/platform/qt/GDBWindow.h

This PR allows to override the GDB's handling of write watchpoints in 2 ways:
- Take control of the GDB's logic that detects if a write watchpoint changed or not as well as prevent a potentially unwanted step into
- The above, but with the addition to also break on nonmodifying watchpoints
The GDB logic part is done by hiding the truth to GDB: we send an S05 instead of a T05watch which forces GDB to stop and not do anything more than that. This can be desired because without this, it's not possible for GDB to know about mgba's savestates which means that say you do a savestate, break on a write watchpoint and then load that state causing the same write, GDB will not be able to detect this and ignore the request to stop (it will just request the inferior to continue). This logic is already …

GDB Stub: Allow to override GDB's handling of write watchpoints

---

src/platform/qt/SettingsView.cpp
src/platform/qt/SettingsView.ui
src/platform/qt/Window.cpp
src/platform/qt/library/LibraryController.cpp
src/platform/qt/library/LibraryController.h
src/platform/qt/library/LibraryGrid.cpp
src/platform/qt/library/LibraryTree.cpp

The following PR implements the requested feature in #2415 .
It adds a new checkbox `Show Filename instead of ROM name in library view` in the Settings page, under Interface:
Smoke tested in manjaro linux with QT 5.15.3
- Verified the option defaults to false.
- Verified the option saves and loads correctly
- Verified that the names change as expected depending on the state of the checkbox.

Qt: Toggle to show filename or gamename in library mode

---

src/platform/qt/CMakeLists.txt
src/platform/qt/CheckBoxDelegate.cpp
src/platform/qt/CheckBoxDelegate.h
src/platform/qt/SettingsView.cpp

> <@endrift> @CodaHighland I just noticed that if you click on the checkbox...box in the logging settings grid, you get this selection frame for the text that isn't present...any idea how to get rid of it? 
> <@endrift> ![image](https://user-images.githubusercontent.com/4741538/154745819-44e5f3c4-af83-4de2-b21c-103accb70257.png)
> <@endrift> you can see it's also taking up space that I don't need to on the right
Qt's item views aren't designed for this specific use case, but they provide accommodations for nonstandard appearances through QAbstractItemDelegate. This PR makes sure that the checkbox is centered within the cell and renders the keyboard focus in a more appropriate manner.
It also makes sure that the keyboard subfocus is updated appropriately, since clicking checkboxes in …

Clean up rendering of logging grid checkboxes

---

src/gba/memory.c

Chunked out from #2181
`rawWrite{16,32}/GBAPatch{16, 32}` is used by the memory editor on Qt, and changes to the VRAM area there were not reflected on the graphical output, whereas palette or OAM writes are. This fixes this inconsistency.

GBA Memory: update the renderer on rawWrite{16,32}/GBAPatch{16,32}

---

src/platform/qt/ScriptingView.cpp

By creating a buffer in the scripting console, then resetting the scripting state, then creating another buffer, the list in the UI gets out of sync with the list of buffers. This fixes that.

Don't crash when resetting scripting UI

---

src/platform/qt/CMakeLists.txt
src/platform/qt/ScriptingController.cpp
src/platform/qt/ScriptingController.h
src/platform/qt/ScriptingTextBuffer.h
src/platform/qt/ScriptingTextBufferModel.cpp
src/platform/qt/ScriptingTextBufferModel.h
src/platform/qt/ScriptingView.cpp
src/platform/qt/ScriptingView.h
src/platform/qt/ScriptingView.ui

Resetting the scripting state crashes mGBA. This PR refactors the way the UI keeps track of the list of buffers by using a list model instead of a QListWidget, enabling the use of standard Qt MVC signals to avoid conflicts.
This PR is mutually exclusive with https://github.com/mgba-emu/mgba/pull/2565 as both solve the same issue in different ways.

refactor the script buffer list into a model

---

README.md

Powershell dictates the requirement where automatic variables need to be wrapped around with curly brackets ({}). This is referenced from the documentation here, as quoted below:  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_variables?view=powershell-7.2
"To create or display a variable name that includes spaces or special characters, enclose the variable name with the curly braces ({}) characters. The curly braces direct PowerShell to interpret the variable name's characters as literals. For example, the following command creates the variable named 'save-items'. The curly braces ({}) are needed because variable name includes a hyphen (-) special character."

doc: Updated the Docker Run command on the README.md

---

include/mgba-util/socket.h
include/mgba/core/scripting.h
include/mgba/internal/script/socket.h
include/mgba/script/context.h
res/scripts/socketserver.lua
res/scripts/sockettest.lua
src/platform/qt/scripting/ScriptingController.cpp
src/script/CMakeLists.txt
src/script/engines/lua.c
src/script/socket.c

This PR provides an event-driven TCP socket API for mGBA scripting. Where the behaviors overlap, it roughly imitates the LuaSocket API, but due to the mGBA scripting core not being yieldable, it can't be a perfect match.
Also included are two sample scripts. Both scripts will log messages received over the socket to the console and will send an input viewer. One script will connect to a server; the other will open a server and listen for incoming connections.
Documentation still needs to be written.

Script bindings for sockets

---

CHANGES
include/mgba/debugger/debugger.h
src/arm/debugger/memory-debugger.c
src/debugger/cli-debugger.c
src/debugger/gdb-stub.c
src/sm83/debugger/memory-debugger.c

These are accessible via the following new CLI debugger commands:
- rw: watchr minAddr maxAddr [cond]
- r: watchr/r minAddr maxAddr [cond]
- w: watchr/w minAddr maxAddr [cond]
- c: watchr/c minAddr maxAddr [cond]
This also makes all watchpoints range watchpoints under the hood.
Preliminary benchmark results:
Time taken to run 10000 frames of Megaman Battle Network 1 (U) with a write watchpoint set at 0x02000000 in milliseconds, 10 runs each:
control (no watchpoint):
[4184, 4185, 4197, 4207, 4220, 4178, 4304, 4226, 4234, 4292]
mean = 4223, stdev = 43.95
old (single address watchpoint):
[4743, 4685, 4679, 4670, 4782, 4704, 4698, 4875, 4746, 4718]
mean = 4730, stdev = 61.67
new (range watchpoint):
[4683, 4691, 4693, 4706, 4782, 4674, 4746, 4768, 4770, 4776]
mean = 4728, stdev = 43.36

Debugger: Add range watchpoints

---

CHANGES
include/mgba/internal/gba/gba.h
src/gba/core.c
src/gba/gba.c

Detect more ELF binaries as valid by checking if the ROM/Multiboot entry branches in the header branch to `e_entry`.
We do this by locating the program header containing the entry branch address, decoding it, checking if it's a branch or branch-with-link instruction, and checking if the branch's target address is `e_entry`.
Should fix detection of Multiboot ROMs built with devkitARM and gba-toolchain.

GBA: Verify ELF entrypoint against ROM header

---

src/platform/libretro/libretro.c

The `SIZE_CART_FLASH1M` constant was renamed to `GBA_SIZE_FLASH1M` in https://github.com/mgba-emu/mgba/commit/8545271e9ee275b9e733bbfa13195365b1fb82e1
These leftovers make the Libretro build fail, when running:
```
cmake -DBUILD_LIBRETRO=ON .. && make
```

Libretro: Fix undeclared constant

---

include/mgba/core/config.h
include/mgba/core/rewind.h
src/core/config.c
src/core/rewind.c
src/core/thread.c
src/platform/qt/ConfigController.cpp
src/platform/qt/SettingsView.cpp
src/platform/qt/SettingsView.ui
src/platform/qt/Window.cpp
src/platform/sdl/main.c

Adds a feature to be able to change the rewind speed.
Settings Page:
Normal Rewind:
Fast Rewind (5x):

Add rewind speed feature

---

CHANGES
src/feature/gui/gui-runner.c

Fixes #2183.
Hi, this is my first PR and @endrift may remember me asking a question or two on the Discord server.
> :warning: I haven't touched C in about... 5 years. And this is my first time making changes to this codebase. Please let me know if I'm doing anything wrong or if I'm making any style mistakes etc.
The change itself is quite small but I'll explain it anyways: extend the `SCREENSHOT_*` enums in the `gui-runner.c` file to include a `SCREENSHOT_STALE`. This is distinct from `SCREENSHOT_INVALID` because we do not want to just draw the current frame onto the background, we want to draw the actual save state screenshot PNG. This is a case that I considered to be equivalent to the `!= SCREENSHOT_INVALID` case in terms of handling, since we basically just want to reload the new PNG …

[UI bug] mGBA doesn't update savestate screenshots until you move the cursor over other savestates

---

src/debugger/gdb-stub.c

The 'g' packet is handled by _readGPRs which has a special case for the PC due to the way the CPU reports the PC value.
This was added by added by a967f9aac433c817fbca981c5e254e5107457f47.
The 'p' packet is handled by _readRegister which did not have this special case for PC. This lead to GDB reporting the correct PC value but LLDB not, as the latter used 'p' instead.
This meant you saw things like this:
0x80002a4 <+16>: str    r0, [sp, #0x4]
0x80002a8 <+20>: bl     0x80001f0      <----------expected to be here.
->  0x80002ac <+24>: b      0x80002b0
Where you expected to be about to bl to another function, but it looked like you had already done it.
And more obviously, when you first attached to the GDB stub, the PC was reported as 4 not 0.

Debugger: Correct PC value when read with 'p' instead of 'g' packet

---

src/debugger/gdb-stub.c

GDB and LLDB will send a ctrl-c character (\x03) to the stub to interrupt it after a continue where it doesn't stop on its own.
E.g.
```
void foo() {
foo2();      // Continue from here.
while (1) {} // Loops here until ctrl-c in the debugger.
}
```
mGBA had code to handle the ctrl-c but because in _continue we set the paused status after calling mDebuggerModuleSetNeedsCallback, the callback was never set so nothing was looking for new messages while we were running. We should instead set the paused state then call mDebuggerModuleSetNeedsCallback.
mDebuggerModuleSetNeedsCallback calls mDebuggerUpdatePaused, and all other calls to mDebuggerUpdatePaused update the paused state before that call so this matches existing usage of that too.
With this fix, after the continue _gdbStubPoll is …

Debugger: Fix interrupt after continue from GDB stub

---

src/debugger/gdb-stub.c

[No-ack mode](https://sourceware.org/gdb/onlinedocs/gdb/Packet-Acknowledgment.html) is an optimization in the GDB protocol when running over a reliable transport mechanism like TCP. It's already implemented in the GDB stub, but the stub doesn't advertise support for it, and it's broken by an off-by-one in a comparison. These fixes make it work as intended.

Debugger: Fix GDB no-ack mode

---

src/platform/qt/main.cpp

The method used to set the window icon (`setWindowIcon`) does not work anymore on Wayland which results in a generic Wayland icon. To set the icon on Wayland, programs should make use of the `setDesktopFileName` method which hints the graphical shell to use the icon specified in the referenced desktop file. This icon is used for the taskbar and the window border / decorations. The described bug occurs especially when using Plasma with Wayland, but other shells using Wayland may be affected too.
The added method was introduced in Qt 5.7 which eventually raises the minimum required version of Qt.
Testing the new commit on Unix resulted in a working icon when using Plasma regardless of Wayland or X11.
If I've missed anything or should fix something, just ask and I'll try.

Qt: Fix generic icon on Wayland

---

res/shaders/gbc-lcd.shader/gbc-lcd-light.fs
res/shaders/gbc-lcd.shader/gbc-lcd.fs
res/shaders/gbc-lcd.shader/license.txt
res/shaders/gbc-lcd.shader/manifest.ini

I wrote a shader that attempts to reproduce the GBC LCD subpixel pattern. It also supports a backlight bleed effect similar to the existing ags001 shader. I used ags001 as a starting point, but otherwise this is new work and not adapted from any other shader. I wrote it primarily for my own use, but I'm guessing it may be of interest to others too.
The license included with the shader is the Unlicense, i.e. the shader is intended to be public domain.
Some credit belongs to this resource: https://gbcc.dev/technology/
Screenshots:
Settings (it doesn't seem like mGBA currently has any easy way to put the options in an intended order?):
1x (not really intended to be used this way, though I'm sure that if you were really determined you could mess with the default settings enough to get …

Res: Add gbc-lcd shader, imitates GBC LCD subpixel arrangement with an optional backlight effect

---

src/debugger/debugger.c
src/platform/qt/GDBWindow.cpp

The current version of mGBA binds the GDB server to 0.0.0.0 which makes it publicly accessible. This allows an outside attacker to connect to mGBA's GDB server and execute arbitrary code. Although the Qt window allows for changing the bind address, there is no way (as far as I am aware) to automatically change the bind address when running mGBA from the command line with the argument --gdb. These commits change the default bind address from 0.0.0.0 to the loopback address 127.0.0.1.

GDB Debugger default to loopback address

---

include/mgba/core/config.h
src/core/config.c
src/platform/qt/ConfigController.cpp

Adds support for specifying an arbitrary portable directory path inside the `portable.ini` file. The path can be either absolute or relative to the executable directory. This allows for the user to consolidate all of the mGBA config and other user data into a single directory wherever they want.
For example, the `portable.ini` could look like this to use a directory named "Data" next to the executable:
```ini
[Portable]
Path=Data
```
Or it could look like this to use a fixed directory on the user's desktop:
```ini
[Portable]
Path=/home/user/Desktop/mgba
```
The PR also includes updates to the Qt UI to support specifying a path when you choose to make the installation portable:

core: Add support for specifying an arbitrary portable directory.

---

src/platform/qt/AudioDevice.cpp
src/platform/qt/AudioDevice.h

So I tried the latest version e3edca1f4168c1eee36cd213ef8d5e91fd35e400 and games do not boot they just hang. This is my attempt to fix it. I don't know if it is correct, but it actually works. Games boot and are playable.

fix hang in AudioDevice

---

src/platform/qt/Window.cpp

I dunno if I did it right but I've managed to rewind while reloading states by accident (well, at first, it's sorta a guilty pleasure now ) so much that I figured this might be worth Fixing™️

Qt: Ignore rewind while loading/saving states

---

include/mgba/internal/gba/cart/vfame.h
src/gba/cart/vfame.c
src/gba/gba.c

The Chinese version of Digimon Sapphire by Vast Fame uses a third set of address reordering modes. This adds those modes and uses the CRC of the ROM to determine which to use. The header of the Chinese version is identical to the English version, so I couldn't use the header name to determine the mode unlike with George Sango.

GBA Memory: Support the Chinese version of Digimon Sapphire by Vast Fame

---

src/platform/qt/KeyEditor.cpp
src/platform/qt/KeyEditor.h

Setting shortcuts does not work properly for me. If I want to assign `Ctrl+F` to some action I press `Ctrl` and it shows "Control" then I press `F` and it shows `F` and finally it assigns `F`. But that's not what I want, I want `Ctrl+F` to be shown and assigned. This PR fixes that.

fix shortcut handling

---

src/gba/core.c

Commit 4c161ff appears to have introduced a performance regression:
* Start mGBA
* Open a GBA ROM
* Open the scripting window
Before 4c161ff, this was instantaneous. After 4c161ff, this takes over 5s on my machine. Profiling reveals that the time is being spent in `mDebuggerLoadARMIPSSymbols`.
It appears that this function is being called to load ARMIPS symbols from the symbol file, even if it's not a .sym file -- which is to say, the GBA ROM itself.

Don't try to load non-.sym files as ARMIPS symbols

---

src/gba/core.c

My previous PR misplaced the `return` statement. Oops.

Fix misplaced return in previous PR

---

src/platform/sdl/sw-sdl2.c

I found that `mSDLSWCreate` is call when `BUILD_GL` not defined, so the flag `SDL_WINDOW_OPENGL` shouldn't be set?
It's really work in my embedded device only after I remove this flag.
https://github.com/mgba-emu/mgba/blob/09f456484cb401856d5dda1af5b80a659b7c2097/src/platform/sdl/main.c#L131-L143

Remove SDL_WINDOW_OPENGL flag in mSDLSWInit

---

src/gba/cart/gpio.c

Resolves #3294
Also see https://github.com/TASEmulators/BizHawk/issues/4060 (this is fixed with this patch).

Fix savestates not writing back GPIO variables to gpioBase

---

src/platform/qt/DisplayGL.cpp

Found while trying to debug a `Couldn't find current GLX or EGL context.` crash
Turns out, the native surface was never updated when the type was changed, the documentation of `QWindow::setSurfaceType` states:
> The [surfaceType](https://doc.qt.io/qt-6/qwindow.html#surfaceType) will be used when the native surface is created in the [create](https://doc.qt.io/qt-6/qwindow.html#create)() function. Calling this function after the native surface has been created requires calling [destroy](https://doc.qt.io/qt-6/qwindow.html#destroy)() and [create](https://doc.qt.io/qt-6/qwindow.html#create)() to release the old native surface and create a new one.
Its probably possible to stop the surface from being created in the first place elsewhere, however this function could be called at any point so …

Qt: Recreate Window to release old surface and create a OpenGL one

---

CMakeLists.txt
src/platform/qt/CMakeLists.txt
src/platform/qt/Window.cpp

command q addictions go crazy sometimes
- Disable a duplicate libraries warning that isn't needed
- Quit using QApplication::quit instead of QWidget::close to prevent closing inside a dialog from crashing the application
- Allow Qt 6 builds to use std::filesystem if the proper macOS SDK version is present
- Stop looking for QtMultimedia plugins if Qt 6 is being used for macOS builds

Fix various macOS related problems

---

src/platform/qt/scripting/ScriptingTextBuffer.cpp

User "Wombat" observed that printing strings containing newlines into a text buffer would word-wrap as if the newlines weren't there. Turns out, ScriptingTextBuffer::print() just wasn't handling newlines at all. This PR causes print() to split the input on newlines and add each section as a separate line in the document.

Qt: handle newlines in TextBuffer print()

---

src/platform/qt/Display.h
src/platform/qt/DisplayGL.cpp
src/platform/qt/DisplayGL.h
src/platform/qt/DisplayQt.h
src/platform/qt/SettingsView.cpp
src/platform/qt/SettingsView.h
src/platform/qt/ShaderSelector.cpp
src/platform/qt/ShaderSelector.h

Killing four birds with one stone:
* Shader uniforms haven't saved since 2017 because the code was written to assume the shader settings had its own OK button. I could have addressed this with a direct function call but I thought a `saveSettingsRequested()` signal would allow future settings panels to be self-contained.
* Unlike basically everything else in the settings window, loading a shader saves the user's choice immediately. This means the Cancel button doesn't undo the action. This PR will still apply the shader changes immediately but it won't save the settings to disk until the user clicks OK or Apply, and the shader changes will be reverted upon clicking Cancel.
* It's kind of annoying to work on shader development with a packaged release of mGBA because you can't select an …

Shader configuration improvements

---

src/platform/qt/scripting/ScriptingTextBuffer.cpp
src/platform/qt/scripting/ScriptingTextBuffer.h

My [previous PR](https://github.com/mgba-emu/mgba/pull/3314) fixed line wrapping for strings with embedded newlines, but in the process it completely broke newline handling.
This PR makes sure that the cursor moves to the next block / a new block after each line.

Qt: honor control characters in ScriptingTextBuffer::print

---

src/script/engines/lua.c

> @CodaHighland would it be possible for you to modify _luaPrintShim to output to stdout if console is nil?

Scripting: send print() to stdout if no console is installed

---

src/platform/qt/SettingsView.cpp
src/platform/qt/SettingsView.h

User "Autofire" in Discord reported a crash when saving settings.
```
Thread 1 "mgba-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff2ba793b in QObject::disconnect (sender=0x555555eec800, signal=0x0, receiver=0x555558be4340, method=0x0)
at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:3280
3280        const QMetaObject *smeta = sender->metaObject();
```
I tracked it down to a use-after-free: `Window::reloadDisplayDriver` calls `SettingsView::setShaderSelector` after destroying the old `ShaderSelector`, but the pointer in `SettingsView` didn't get cleared. Fortunately, QPointer exists for exactly this.

Qt: Fix use-after-free in shader settings

---

src/gba/cart/gpio.c

Unused GPIO bits are not writable and always return 0. This is documented on gbatek and I've confirmed this is the correct behavior on my own Emerald cartridge.

Mask away unused GPIO bits

---

include/mgba/internal/gba/cart/gpio.h
include/mgba/internal/gba/serialize.h
src/gba/cart/gpio.c
src/gba/serialize.c

Regardless of direction, a write to GPIO data actually succeeds fully with all 4 bits. However, this does not directly touch the pin state. It instead places it into an internal write only latch. This latch asserts bits onto the pin state if direction allows for such, otherwise the other side (e.g. RTC) will be the one asserting bits (but this does not end up touching the internal write latch).
The implementation here is likely not entirely accurate for direction changes from out to in (as that depends on each external device implementation), but it should be correct for in to out changes.

Implement GPIO internal write latch

---

src/platform/qt/FrameView.cpp

The base video size of the Game Boy core is the Super Game Boy’s resolution of 256×224 pixels. Previously frames were exported at that size, leading to a 160×144 frame surrounded by uninitialized memory.
This assumes that the base size is always greater or equal to the current video size.
-------------------------
Examples of bad exports:
Cropped:
With border:

Crop frame view exports to current video size

---

src/platform/qt/library/LibraryModel.cpp
src/platform/qt/library/LibraryModel.h

Discord user "NisioAyano" reported that between a75c6c41e and d79579d1c, the library view started rendering a lot of blank lines even though the underlying data was still correct.
I tracked this down to a mistake in https://github.com/mgba-emu/mgba/pull/3463.

Qt: fix blank rows in library rendering

---

src/platform/qt/library/LibraryController.cpp

User "Menergy" on Discord noticed that the new library code can't launch games.
Upon further investigation, this is because a zero-initialized struct is no longer sufficient to call `mLibraryGetEntries` without any constraints.

Qt: don't restrict by model when loading from the library

---

src/util/vfs/vfs-mem.c

Truncation here is limited to buffer size (allowing for shrinking but not growing the VFile size)

Allow truncation to work within VFileFromMemory

---

include/mgba/internal/gba/cart/gpio.h
include/mgba/internal/gba/serialize.h
src/gba/cart/gpio.c
src/gba/serialize.c

Unsure if all of this is entirely right (haven't ran any tests to confirm behavior here). Fixes RTC within Pokemon games (and maybe other games) due to the added write latch code adding a _readPins call to direction writes.

RTC state machine improvements

---

src/platform/qt/AudioDevice.cpp
src/platform/qt/AudioProcessorQt.cpp
src/platform/qt/AudioProcessorSDL.cpp
src/platform/qt/CheatsModel.cpp
src/platform/qt/CheatsView.cpp
src/platform/qt/CoreController.cpp
src/platform/qt/CoreManager.cpp
src/platform/qt/DebuggerConsoleController.cpp
src/platform/qt/DisplayGL.cpp
src/platform/qt/GBAApp.cpp
src/platform/qt/GIFView.cpp
src/platform/qt/InputController.cpp
src/platform/qt/LogController.cpp
src/platform/qt/LogController.h
src/platform/qt/MemoryAccessLogController.cpp
src/platform/qt/MemoryDump.cpp
src/platform/qt/MemoryModel.cpp
src/platform/qt/MultiplayerController.cpp
src/platform/qt/PaletteView.cpp
src/platform/qt/SaveConverter.cpp
src/platform/qt/VideoView.cpp
src/platform/qt/Window.cpp

`LOG()` can't easily be used in a unit test context because `LogController` has a lot of transitive dependencies, some of which can't easily be constructed without standing up an entire `GBAApp`.
To break this dependency, this PR uses `qInstallMessageHandler` so that `qDebug()` et al are redirected to mGBA's logging system. Unit tests won't be constructing a `LogController` so the message handler is not installed and the default Qt logging functionality will be used instead.
This has the additional benefit that any logging that Qt itself might generate will show up in mGBA's logging (if enabled by the filters).

Qt: route Qt logging to mGBA's logging system

---

src/platform/qt/CMakeLists.txt
src/platform/qt/CheckBoxDelegate.cpp
src/platform/qt/ConfigController.cpp
src/platform/qt/Window.cpp
src/platform/qt/scripting/AutorunScriptModel.cpp
src/platform/qt/scripting/AutorunScriptModel.h
src/platform/qt/scripting/AutorunScriptView.cpp
src/platform/qt/scripting/ScriptingController.cpp
src/platform/qt/scripting/ScriptingController.h
src/platform/qt/test/autoscript.cpp

This PR depends on https://github.com/mgba-emu/mgba/pull/3483 as a prerequisite. (These changes will appear in this PR. You can view the last commit to review the changes in isolation.)
Qt's item models are notoriously tricky to get right. This PR adds some unit tests for `AutorunScriptModel` and makes sure all of them pass. It also cleans up the boundaries of `AutorunScriptModel` so that it can be unit tested.
Fixes of note:
* `setData` was not emitting `dataChanged`
* `removeRows` was not emitting `aboutToRemoveRows` / `rowsRemoved`
* `removeRows` did not have appropriate bounds checking, so clicking the Remove button would crash if no scripts were selected
* `moveRows` did not implement the correct API contract (which is painfully difficult to begin with)
* `moveRows` was not emitting …

Qt: improve AutorunScriptModel, add unit tests

---

src/debugger/gdb-stub.c

When debugging with GDB closing mGBA doesn't send the GDB end session command (`$W00`); it only closes the socket (which is not enough)
The effect of this is when using GDB to debug, if mGBA is closed the GDB session may stay open. This is obvious when debugging GBA programs with IDEs such as Visual Studio Code or CLion.
Information on the W AA process exit stop packet:
https://sourceware.org/gdb/current/onlinedocs/gdb.html/Stop-Reply-Packets.html
Here's a video showing the issue on mGBA master versus this branch - notice how when closing mGBA the debugger tools hang around and require an explicit press of the "Stop" button, which does not stop the debugging until it times out with a `-1`
https://github.com/user-attachments/assets/74e61b60-215f-41b4-842f-46c332e1de44
However closing mGBA …

Send hangup `$W00` to GDB
