- res/mgba-qt.desktop
lintian from debian 8 will complain the missing keyword
> Added Keyword and Comment to desktop entry.

- src/platform/3ds/3ds-memory.c
- src/platform/3ds/3ds-vfs.h
- src/platform/3ds/CMakeLists.txt
- src/platform/3ds/CMakeToolchain.txt
- src/platform/3ds/ctr-gpu.c
- src/platform/3ds/ctr-gpu.h
- src/platform/3ds/gui-font.c
- src/platform/3ds/main.c
- src/platform/3ds/uishader.vsh
After much blood, sweat and tears. Replaces sf2d lib with custom code, which we can hopefully also scrap soon and replace with ctrulib-refactor and fincs-powered GPU code instead.
> 3DS GPU rewrite

- CHANGES
- src/debugger/gdb-stub.c
Add support for GDB memory and register writing commands.
> Debugger: Support additional GDB stub packets

- CHANGES
- src/platform/qt/ts/mgba-de.ts
This is my German translation of the mGBA Qt GUI. It is pretty much complete, there are only a few strings in the IOViewer missing that I am currently unable to translate due to a lack of understanding how those things work. I will try to figure this out as soon as possible.
There are currently 17 untranslated strings and 11 unfinished (aka questionable) strings left. I merged in the missing strings KDDLB found yesterday.
Feedback is greatly appreciated.
> Qt: Add German GUI translation

- src/platform/qt/ts/mgba-de.ts
Some new strings added and a few strings polished.
> Qt: Update German GUI translation

- src/gba/core.c
Fixes build with GB core disabled
> GBA: Fix typo of GBAIsBIOS

- src/core/input.c
- src/platform/qt/GBAKeyEditor.cpp
- src/platform/qt/GameController.cpp
Increasingly verbose explanations included in the individual commits.
> Fix sprite window crash; fix poor handling of multiple gamepads in Qt

- CHANGES
- CMakeLists.txt
- src/platform/qt/CMakeLists.txt
- src/platform/qt/DisplayGL.cpp
- src/platform/qt/DisplayGL.h
- src/platform/qt/GBAApp.cpp
- src/platform/qt/Window.cpp
- src/platform/qt/Window.h
> Qt: Various cleanups and bugfixes.

- res/shaders/lcd.shader/lcd.fs
- res/shaders/lcd.shader/manifest.ini
- res/shaders/motion_blur.shader/manifest.ini
- res/shaders/motion_blur.shader/motion_blur.fs
- res/shaders/scanlines.shader/manifest.ini
- res/shaders/scanlines.shader/scanlines.fs
- res/shaders/soften.shader/manifest.ini
- res/shaders/soften.shader/soften.fs
- res/shaders/vba_pixelate.shader/manifest.ini
- res/shaders/vba_pixelate.shader/vba_pixelate.fs
- res/shaders/vignette.shader/manifest.ini
- res/shaders/vignette.shader/vignette.fs
Added simplest possible configurable shaders.
(I think it will be more useful in this repository than just on my HDD. :))
> New shaders

- src/platform/qt/SettingsView.cpp
No idea how I missed this in the library PR.
> Qt: Actually load the libraryStyle setting.

- src/platform/qt/main.cpp
> Qt: Fix SDL < 2 build.

- CHANGES
- src/arm/isa-arm.c
> GBA: Fix MSR when execution mode changes to Thumb

- README.md
- README_DE.md
- src/platform/qt/AboutScreen.ui
- src/platform/qt/ts/mgba-de.ts
- src/platform/qt/ts/mgba-es.ts
I think the copyright year should be updated to 2018 :)
> All: Update copyright year to 2018

- opt/libgba/mgba.c
Fd changed from int to void* so a change is needed to make the debug library work :)
> Correct debug lib

- README.md
- README_DE.md
> Fix a build error on macOS Sierra and High Sierra #798

- src/platform/qt/ts/mgba-de.ts
- src/platform/qt/ts/mgba-es.ts
- src/platform/qt/ts/mgba-fr.ts
- src/platform/qt/ts/mgba-it.ts
I also updated the `ts` files for the other translations.
> Qt: Updated Spanish translation

- src/platform/qt/ts/mgba-zh-cn.ts
Hi, there
The PR contains my Simplified Chinese translation strings of the Qt GUI. Most strings of the main menu  is complete.
Any comments and suggestions are welcome!
> Qt: Add Chinese translation

- src/platform/qt/main.cpp
Fix blurry icons on buttons with High DPI screens.
Before:
After:
> HiDPI support for Qt GUI

- src/platform/qt/ts/mgba-de.ts
Just a simple translation fix.
> Fix German save state translation

- src/platform/qt/ts/mgba-it.ts
My way to contribute to this tool :-)
> Qt: Update Italian GUI translation

- src/platform/qt/ts/mgba-fr.ts
This pull request update the French translations for the Qt platform.
> Qt: Update French translations

- src/platform/qt/ts/mgba-zh_CN.ts
- remove unnecessary whitespace
- fix non-quote punctuation
> Qt: Update Simplified Chinese GUI translation

- src/platform/qt/ts/mgba-ja.ts
Japanese translation by JaKid20
> Qt: Add Japanese GUI translation

- src/platform/qt/ts/mgba-zh_CN.ts
- New translations
- Delete unused entries
- Fix typos and invaild lines, fixes #1845
> General fixes to Simp. Chinese translation

- src/platform/qt/ts/mgba-zh_CN.ts
> Some small fixes.

- src/platform/qt/ts/mgba-zh_CN.ts
- New translations
- Delete unused entries
- Fix typos and invaild lines
> Qt: General fixes to Simp. Chinese translation

- README_ZH_CN.md
- src/platform/qt/ts/mgba-ja.ts
- src/platform/qt/ts/mgba-zh_CN.ts
- New ReadMe file (`README_ZH_CN.md`) in Simp. Chinese.
- Updated Simp. Chinese translation.
- Revamped (but partially) Japanese translation based on `mgba-template.ts`.
> New README_ZH_CN.md and updates to Simp. Chinese and Japanese translation

- README.md
- README_DE.md
- README_ES.md
- README_ZH_CN.md
Not a lot changed. Most importantly, it's `pkgconf` now.
> Simplified MSYS2 intructions

- include/mgba/internal/gba/audio.h
- src/gba/audio.c
- src/gba/io.c
Check the individual commit messages for more details.
> GBA: Fix wave RAM write/read behaviour

- src/feature/gui/gui-config.c
- src/feature/gui/gui-runner.c
Adds the fast forward mute feature as requested in #2150. 
Please note I'm unexperienced coding in C; I did try to adhere to the coding style / standards.
I'd love to hear feedback on this. You can also make edits yourself if you prefer. Thanks!
> mGUI: Add fast forward mute

- src/platform/qt/ts/mgba-pt_BR.ts
Updated brazilian portuguese translation.
> Updated translation

- src/platform/qt/ts/mgba-zh_CN.ts
Review and updated language file.
> Update new translated Simplified Chinese entry

- res/shaders/tv-mode.shader/manifest.ini
- res/shaders/tv-mode.shader/tv.fs
Someone asked me to "port" this display filter from VBA, so here it is. Still as simple as possible.
---
> Res: Add TV Mode shader

- CHANGES
- src/gba/core.c
> Check gba->mbVf for force skipping the BIOS

- src/platform/qt/ForwarderView.ui
This one is just a small typo.
> Qt: Fix typo in forwarder ui

- src/platform/qt/Window.cpp
Adds shortcuts to increment/decrement fast forward speed.
Resolves the following issue:  #2830
> Feature: shortcuts to increment fast forward speed

- src/gba/overrides.c
> Add Goodboy Galaxy to overrides

- src/platform/qt/Display.cpp
- src/platform/qt/ShaderSelector.cpp
> Fix #3078  issue

- src/platform/3ds/main.c
- src/util/gui/menu.c
> Add 3x sharp bilinear upscaling make it the default instead of 2x

- README_ZH_CN.md
previous translation in zh_cn is good but is kind of outdated
sync with current readme and fix minor erorrs
> update readme in zh_cn

- src/platform/qt/ConfigController.cpp
- src/platform/qt/FrameView.cpp
- src/platform/qt/MapView.cpp
- src/platform/qt/MemoryModel.cpp
- src/platform/qt/SaveConverter.cpp
- src/platform/qt/Swatch.cpp
- src/platform/qt/TilePainter.cpp
- src/platform/qt/Window.cpp
- src/platform/qt/main.cpp
This fixes all Qt6 deprecation warnings and keeps compatibility with Qt5.
> fix Qt6 deprecation warnings

- src/platform/qt/KeyEditor.cpp
> fix assignment of modifier keys

- src/platform/qt/KeyEditor.cpp
> fix numpad shortcuts

- src/gba/cart/gpio.c
> Serialize light counter to the correct bitfield

- src/debugger/cli-debugger.c
> Debugger: CLIDebugger - fix bug CLIDebuggerRunCommand always return false

- CHANGES
- include/mgba/debugger/debugger.h
- src/arm/debugger/debugger.c
- src/arm/debugger/memory-debugger.c
- src/debugger/cli-debugger.c
Command:
- Enable:   enable <breakpoint/watchpoint id>+
eb <breakpoint/watchpoint id>+
- Disable:  disable <breakpoint/watchpoint id>+
db <breakpoint/watchpoint id>+
Example: eb 1; disable 1 2 3;
> Debugger: Support enable/disable breakpoint/watchpoint

- src/platform/qt/scripting/AutorunScriptModel.cpp
- src/platform/qt/test/autoscript.cpp
- src/platform/qt/test/library.cpp
Fixes https://github.com/mgba-emu/mgba/issues/3593
> Test: fix Qt6 test failures
